"use client";

import { ThemeProvider as NextThemesProvider } from "next-themes";
import { useEffect, useState, createContext, useContext } from "react";
import ResumeModal from "./components/ResumeModal";

// Suppress React 19 / Next.js 16 script-tag warning generated by next-themes in development
if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  const originalError = console.error;
  console.error = (...args) => {
    if (
      typeof args[0] === "string" &&
      (args[0].includes("Encountered a script tag while rendering React component") ||
       args[0].includes("Scripts inside React components are never executed"))
    ) {
      return;
    }
    originalError.apply(console, args);
  };
}

const ResumeModalContext = createContext({
  openResume: () => {},
  closeResume: () => {},
  isResumeOpen: false,
  isContactHighlighted: false,
  triggerContactHighlight: () => {},
});

export const useResumeModal = () => useContext(ResumeModalContext);

export function Providers({ children }) {
  const [mounted, setMounted] = useState(false);
  const [isResumeOpen, setIsResumeOpen] = useState(false);
  const [isContactHighlighted, setIsContactHighlighted] = useState(false);

  const openResume = () => setIsResumeOpen(true);
  const closeResume = () => setIsResumeOpen(false);

  const triggerContactHighlight = () => {
    const contactSection = document.getElementById("contact");
    if (contactSection) {
      contactSection.scrollIntoView({ behavior: "smooth" });
    }
    setIsContactHighlighted(true);
    setTimeout(() => {
      setIsContactHighlighted(false);
    }, 2000);
  };

  // Prevent hydration mismatch by waiting until mounted
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return <div style={{ visibility: "hidden" }}>{children}</div>;
  }

  return (
    <NextThemesProvider attribute="class" defaultTheme="dark" enableSystem={false}>
      <ResumeModalContext.Provider value={{ 
        isResumeOpen, 
        openResume, 
        closeResume, 
        isContactHighlighted, 
        triggerContactHighlight 
      }}>
        {children}
        <ResumeModal isOpen={isResumeOpen} onClose={closeResume} />
      </ResumeModalContext.Provider>
    </NextThemesProvider>
  );
}
