"use client";

import { ThemeProvider as NextThemesProvider } from "next-themes";
import { useEffect, useState, createContext, useContext } from "react";
import ResumeModal from "./components/ResumeModal";

// Suppress React 19 / Next.js 16 script-tag warning generated by next-themes in development
if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  const originalError = console.error;
  console.error = (...args) => {
    if (
      typeof args[0] === "string" &&
      (args[0].includes("Encountered a script tag while rendering React component") ||
       args[0].includes("Scripts inside React components are never executed"))
    ) {
      return;
    }
    originalError.apply(console, args);
  };
}

const ResumeModalContext = createContext({
  openResume: () => {},
  closeResume: () => {},
  isResumeOpen: false,
});

export const useResumeModal = () => useContext(ResumeModalContext);

export function Providers({ children }) {
  const [mounted, setMounted] = useState(false);
  const [isResumeOpen, setIsResumeOpen] = useState(false);

  const openResume = () => setIsResumeOpen(true);
  const closeResume = () => setIsResumeOpen(false);

  // Prevent hydration mismatch by waiting until mounted
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return <div style={{ visibility: "hidden" }}>{children}</div>;
  }

  return (
    <NextThemesProvider attribute="class" defaultTheme="dark" enableSystem={false}>
      <ResumeModalContext.Provider value={{ isResumeOpen, openResume, closeResume }}>
        {children}
        <ResumeModal isOpen={isResumeOpen} onClose={closeResume} />
      </ResumeModalContext.Provider>
    </NextThemesProvider>
  );
}
